### ISSUE TITLE
Support forking Tomcat into separate JVM, and specifying javaArgs for it

### ISSUE THREAD

**Issue by sslavic** [t7mp/t7mp#10]
I'd like to use the t7mp plugin to start Tomcat in JVM separate from Maven build, and to be able to configure arguments for forked JVM so that I can add javaagent like jacoco for code coverage, and so that I can control Tomcat JVM memory requirements without affecting Maven build.

At the moment it seems Tomcat runs in same process as the Maven build, so configuring javaagenet just for the Tomcat/webapp is not possible. Same goes for JVM memory, now it seems one can set memory parameters through MAVEN_OPTS, which apply to all JVM instances created by the build (can be many of them, e.g. created from test plugins), and if only Tomcat requires extra memory, all JVM instances would have to be given extra memory since they share same configuration (MAVEN_OPTS).

Adding support for "fork" and "javaArgs" configuration attributes would do the trick.

Regards,
Stevo.

**Comment by t7mp** [comment]
Hi Stevo,

with the latest version (0.9.8-SNAPSHOT) you can run the tomcat instance in a separate vm. What's not possible at the moment, is to configure 'javaArgs'. Maybe a bit later ;-). So for now you can try to use a not so well known feature in tomcat. Use the 'setenv.sh'. In the 'forked mode' we run an process as normal 'catalina.sh' invocation. This 'catalina.sh' calls the 'setenv.sh', if it exist. But it does not come with the default tomcat distribution.

Please, let us know whats going wrong or don't work as expected.

Cheers
Jörg

**Comment by marcobuss** [comment]
This can be achived by using the t7:run-forked goal and a setenv.bat or setenv.sh. An example can be found in the examples repo.
