### ISSUE TITLE
Create a mailing-list for t7mp users

### ISSUE THREAD

**Issue by sslavic** [t7mp/t7mp#11]
Please create a mailing-list where t7mp users and commiters could discuss t7mp related topics.

Regards,
Stevo.

**Comment by marcobuss** [comment]
Any suggestions for a maling-list provider wich offers free mailing lists.

I have created a t7mp group on google groups https://groups.google.com/group/t7mp but I`am not so happy with it. You need a Google account to contribute. I also know that yahoo also offers groups but the same problem like Google. You need an account.

**Comment by sslavic** [comment]
Google account is not needed to subscribe, post new or reply to existing topics, and unsubscribe from google group.

Here's subscribe FAQ:
http://groups.google.com/support/bin/answer.py?hl=en&answer=46606

Here's unsubscribe FAQ:
http://groups.google.com/support/bin/answer.py?hl=en&answer=46608

Here's how to post new/reply FAQ:
http://groups.google.com/support/bin/answer.py?answer=46242

Here's FAQ on when google account is needed:
http://groups.google.com/support/bin/answer.py?hl=en&answer=46438

Create a wiki page on github with mailing-list info, including these FAQ details, and there shouldn't be a problem.

Regards,
Stevo.
