### ISSUE TITLE
Support for a different/non-standard context definition file

### ISSUE THREAD

**Issue by AlexanderHorz** [t7mp/t7mp#14]
The web app's default context definition is located in "src/main/webapp/META-INF/context.xml" (and packed into the war file).

For tests, I would like to deploy a different context definition (without affecting the "mvn package" result). 

Tomcat Maven Plugin offers an option (cf. http://mojo.codehaus.org/tomcat-maven-plugin/examples/deployment.html):
        <configuration>
          <contextFile>path/to/my/contextFile.xml</contextFile>
        </configuration>
Is there a corresponding option for t7mp (maybe in the near future)?

**Comment by t7mp** [comment]
Hi Alexander,
we are always interested to push new features into the plugin. Can you please describe a bit more in detail what you want to do? As far as I understand, the 'context.xml'-File in src/main/webapp/META-INF will be overriden by the configured special 'context.xml'-File? Is that correct? Is it possible for you to show or mention the differences between your normal and your test 'context.xml'-File. Maybe you can solve your needs with filters and placeholder in a normal maven way.

Regards
Joerg

**Comment by AlexanderHorz** [comment]
Jörg,

> As far as I understand, the 'context.xml'-File in src/main/webapp/META-INF
> will be overriden by the configured special 'context.xml'-File?
> No, the standard "context.xml" is still packed into the war file. However,
> when performing "mvn test", you may deploy a different context file by
> pointing to it in the plugin configuration.
> 
> Is it possible for you to show or mention the differences between your normal
> and your test 'context.xml'-File. Maybe you can solve your needs with filters
> and placeholder in a normal maven way.
> The standard context file shall provide the default configuration, and shall
> be put into the war file. The test context file, however, shall provide a
> configuration suitable for the "mvn test" test.

In my specific case, a context parameter points to the configuration file tree
of my web application.

By default, this configuration tree is located in "/etc/opt/${package}/..."
(according to the Filesystem Hierarchy Standard), and this default tree is
initialyy empty. For local tests (using "mvn test") however, an a priori popu-
lated configuration tree has to be deployed (via non-standard parameters in the
test context file).

The question is: How can I test my webapp and also preserve the default context
file in the war archive?

Thamks for you support,

```
Alexander
```

**Comment by AlexanderHorz** [comment]
Jörg,

> Can you please describe a bit more in detail [...]
> I've just recognized that my initial github message has been
> partially destroyed. Please compare to my comment at the
> bottom of http://code.google.com/p/t7mp/wiki/Configuration

Thanks, again

```
Alexander
```

**Comment by t7mp** [comment]
Hi Alexander,

please try the latest snapshot (0.9.8-SNAPSHOT) and configure an 'testContextFile'-element as in https://github.com/t7mp/t7mp/tree/master/src/it/testContextFile/pom.xml.

Does this help? Any errors?

MfG
Joerg

**Comment by AlexanderHorz** [comment]
Jörg,

> please try the latest snapshot (0.9.8-SNAPSHOT) and [...]

Perfect: It works as expected!

Nevertheless, please consider renaming the "testContextFile" element to "contextFile" for enhanced usability.

Vielen Dank für deine Mühe,

```
Alexander
```
