### ISSUE TITLE
Question/proposals on t7mp goals for tomcat control

### ISSUE THREAD

**Issue by AlexanderHorz** [t7mp/t7mp#15]
Jörg,

could you please explain the meaning/rational of the "run", "stop", and "stop-server" goals? I'm a little bit confused about the actual design.

First, the difference between goals "t7.stop" and "t7:stop-server" is not clear to me. Could you please explain?

Second, I would like to propose some changes for better usability of t7mp.

From my personal point of view, there are two use cases ("modes") for t7mp usage in a maven project:
(1) "batch" mode: Tomcat is started "in the background" (with "tomcatSetAwait" set to "false"), integration tests are performed, and tomcat is stopped, finally.
(2) "interactive" mode: Tomcat is started "in the foreground" for interactive eploration (with "tomcatSetAwait" set to "true"); this mode is useful for debugging, e.g. prior to programming (additional) integration tests

So, from my point of view, the following three t7mp goals would be favourable:
(a) "t7:start": Start Tomcat in batch mode
(b) "t7:stop": Stop Tomcat in either mode
(c) "t7:run":   Start Tomcat in interactive mode
Additional goals are not required (from my personal point of view, of course).

Today, goal (a) "t7:start" is currently implemented by "t7:run" with "tomcatSetAwait" set to "false", and goal (c) is  currently implemented by "t7:run" with "tomcatSetAwait" set to "true". However, introducing different goals instead of relying on specific configuration elements would allow for (slightly) more concise "pom.xml" files, and ... (generally enhanced usability).

In addition, goal (b) "t7:stop" is currently implemented by "t7:stop-server", while there is already a goal "t7:stop" with unknown meaning. Intuitively, a user would expect "t7:stop" to have meaning (b).

What do you think about  my proposal?

Vielen Dank für deine Mühe!

Alexander

**Comment by t7mp** [comment]
Hi Alex,

thanks for your interest in t7mp. Well, at the moment there is only one mojo-implementation to start the tomcat-server. You are doing this with 't7:run'. The stop-Mojos are relicts from the early stages of the plugin. The are normally not needed anymore. What are the differences? 't7:stop' takes a reference to the running tomcat-instance from the plugin-context and shutdown the instance. Today, there are shutdownhooks registered. So, when the process terminates (successfull build, failure or ctrl+c) shutdownhooks run and terminates the instance. 't7:stop-server' does something different. It uses the tomcat shutdown port (8005 is the default) and sends an shutdown-command over the network. So it would be possible to shut down multiple instances running on the same machine or in the intranet (only if the servers are configured to accept requests from the intranet). But i think nobody needs this mojo in reality. So, both could be removed.

Maybe we should use a property 'mode' with possible values are 'background' and 'foreground' (default). This property will replace the property 'tomcatSetAwait' (did you understand what this means?  ;-)  ).

The 'run'-goal should be as is.

Hope that clarify some points.

MfG
Jörg

**Comment by AlexanderHorz** [comment]
Jörg,

thanks for your comment.

> What are the differences? 't7:stop' takes a reference to the running
> tomcat-instance from the plugin-context and shutdown the instance.
> Today, there are shutdownhooks registered. So, when the process
> terminates (successfull build, failure or ctrl+c) shutdownhooks run
> and terminates the instance.
> I understand, that "t7:stop" is an implementation of the goal "stop the
> embedded tomcat".

## However, if tomcat is started (in the foreground) using command

## mvn t7:run &

i.e. the "mvn" process has been sent to the background, a subsequent
"mvn t7:stop" fails.

> 't7:stop-server' does something different. It uses the tomcat
> shutdown port (8005 is the default) and sends an shutdown-command
> over the network.
> That's exactly the reason why "t7:stop-server" works even in the scenario
> sketched above.

Of course, concurrently running tomcat instances may conflict on the
shutdown port. So, you may prefer "t7:stop" for concurrently running
tomcats. However, these concurrently running tomcats may also conflict
on their HTTP ports. Hence, if you want to run multiple tomcats concur-
rently, you have to configure each instance with individual HTTP ports.
BUt then, its easy to confiure individual shutdown ports, too.

Then, goal "t7:stop-server" perfectly works, even when multiple tomcat
instances are concurrently running, while "t7:stop" doesn't.

> Maybe we should use a property 'mode' with possible values are
> 'background' and 'foreground' (default). This property will replace
> the property 'tomcatSetAwait' (did you understand what this means?
> IMHO, a separat "Mojo" for each use case would be favorable.

## The "RunMojo.execute()" method should be simplified as follows:

/*\*  @goal run [...] */
public class RunMojo extends AbstractT7Mojo {
    [...]
    public void execute() throws MojoExecutionException, MojoFailureException {
        [...]
        try {
            bootstrap.init();
            final TomcatShutdownHook shutdownHook = new TomcatShutdownHook(bootstrap);
            ScannerSetup.configureScanners(shutdownHook, this);
            bootstrap.start();
            getPluginContext().put(T7_BOOTSTRAP_CONTEXT_ID, bootstrap);
            Runtime.getRuntime().addShutdownHook(shutdownHook);
            getLog().info("Tomcat started");
        } catch (Exception e) {
            throw new MojoExecutionException(e.getMessage(), e);
        }
    }
    [...]

## }

## The "StartMojo.execute()" method should look like this:

/*\*  @goal start [...] */
public class StartMojo extends AbstractT7Mojo {
    [...]
    public void execute() throws MojoExecutionException, MojoFailureException {
        [...]
        try {
            bootstrap.init();
            final TomcatShutdownHook shutdownHook = new TomcatShutdownHook(bootstrap);
            ScannerSetup.configureScanners(shutdownHook, this);
            Runtime.getRuntime().addShutdownHook(shutdownHook);
            bootstrap.setAwait(true);
            bootstrap.start();
        } catch (Exception e) {
            throw new MojoExecutionException(e.getMessage(), e);
        }
    }
    [...]

## }

This design makes the semantics more explicit than the current design of
relying on an additional configuration element. And the pom configuration
would be less verbose!

In essence, I would strongly argue for the modified set of goals
(a) Start Tomcat in batch/background mode
(b) Stop Tomcat in either mode (using the shutdown port)
(c) Run/start Tomcat in interactive/foreground mode

From my pint of view/understanding, this design is straight forward. But,
I might have missed some important point?

Beste Grüße

```
Alexander
```

**Comment by AlexanderHorz** [comment]
Jörg,

two additions to my previous posting:

(1) There is a minor error: The respective execute methods should be swapped (my follow-up email on
that vanished)
(2) By "multiple tomcat instances" I think about multiple Maven projects run manually as well as of "Continuous Integration" using e.g. Hudon or Jenkins.

Grüße,
    Alexander

**Comment by t7mp** [comment]
Hi Alexander,

thanks for you thoughts. I never did such a thing ' mvn t7:run & ' to put that mvn-process to the background. Why are you doing that. Did you read it somewhere?

If you are interested in a configuration for painless setup for multiple concurrent t7mp in Jenkins, I can provide an example in the example-repository in the near future.

For the implementation of the different goals you mention above, I will think about it,ok? ;-)
Better way could be, you send an merge-request with your implementation.

MfG
Jörg

**Comment by t7mp** [comment]
Hi Marco,

can you please comment to this issue and delete the 1 goal we discussed last week?

Thank you.

MfG
Jörg
