### ISSUE TITLE
Preferred way of discussion/collaboration (on best practice)

### ISSUE THREAD

**Issue by AlexanderHorz** [t7mp/t7mp#16]
Jörg,

currently, I'm working on a best practice for webapp development using maven and t7mp.

From my point of view, there are many open issues deserving discussion/collaboration in the t7mp community. Hence, I would like to collaboratively develop and document a simple but complete demo project exhibiting all aspects of this best practice.

I'm new to github, hence do not know about the "accepted" way of collaboration. The (concise) result of the discussion (but not the different arguments and proposals!) might be put into a github wiki page. Discussing by posting issues might not be appropriate.

Would you propose a specific way/platform of collaboration?

Beste Grüße

Alexander

**Comment by t7mp** [comment]
Hi,

what do you think do we need?
As many other projects on github the wiki should be the preferred way for documentation.
For discussions there is a googlegroup out there.
An example-webapp-project would be fine, and I created an repository for that to fork. It should be an multi-module-project for multiple examples.

What are your experiences with collaboration tools? What do you prefer?

MfG
Jörg

**Comment by AlexanderHorz** [comment]
Jörg,

> what do you think do we need?
> [...]
> What are your experiences with collaboration tools? What do you prefer?
> Unfortunately, I'm currently not able to respond.

I'll come back to you in about 1-2 weeks.

Beste Grüße

```
Alexander
```

**Comment by t7mp** [comment]
Hi Alexander,

if you have any input for us.
If not, we will close this issue when 0.9.8 is released.

You are welcome to improve the project.

MfG
Jörg

**Comment by AlexanderHorz** [comment]
Hi Jörg,

sorry for answering so late: I've been on vacation, and offline.

Due to unecpected work overload, I have not been able to work on the best
practice, and I expect to be unable to work on it in the near future.

However, I'll come back to this issue later this year.

Best,

```
Alexander
```

**Comment by jbellmann** [comment]
Hi Alexander,

no problem.
Your are welcome to bring this topic back on top at any time you want in the future.

Cheers
Jörg
