### ISSUE TITLE
support dependency management in libs

### ISSUE THREAD

**Issue by amirkibbar** [t7mp/t7mp#17]
hi,

i'd like to be able to use artifacts in the libs section without directly mentioning their version. Instead i'd like the jarArtifact respect the dependencyManagement in this or a higher pom. For example in a parent pom:
<dependecyManagement>
    <dependencies>
        <groupId>com.h2database</groupId>
        <artifactId>h2</artifactId>
        <version>1.3.155</version>
    </dependencies>
</dependencyManagement>

then in some child pom:
<build>
        <plugins>
            <plugin>
                <groupId>com.googlecode.t7mp</groupId>
                <artifactId>maven-t7-plugin</artifactId>
                <configuration>
                    <libs>
                        <jarArtifact>
                            <groupId>com.h2database</groupId>
                            <artifactId>h2</artifactId>
                        </jarArtifact>
                    </libs>
                </configuration>
            </plugin>
        </plugin>
</build>

is this possible?

thanks

**Comment by t7mp** [comment]
Hi,
at the moment, this is not possible. But that is not a problem. A better approach could be to declare the version in the 'properties'-section and then use placeholders. Maybe:

<properties>
  <h2.version>1.3.155</h2.version>
</properties>

then do the following:

<dependecyManagement>
<dependencies>
<groupId>com.h2database</groupId>
<artifactId>h2</artifactId>
<version>${h2.version}</version>
</dependencies>
</dependencyManagement>}

and 

<plugin>
<groupId>com.googlecode.t7mp</groupId>
<artifactId>maven-t7-plugin</artifactId>
<configuration>
<libs>
<jarArtifact>
<groupId>com.h2database</groupId>
<artifactId>h2</artifactId>
<version>${h2.version}</version>
</jarArtifact>
</libs>
</configuration>
</plugin>

Doing it this way should work for you. It's a cleaner way, more maven-like, isn't it?

Jörg

**Comment by amirkibbar** [comment]
Hi,

Thanks for the response. I've already used a property to do this (before you suggested it :) ), but this is not always the better way. I'm using a 3rd pom which I use to import dependency management from (see maven's import scope), so the properties in the imported pom are not exposed to the child pom. The only way to do it us for the t7 to support regular dependency version resolution.

I'd appreciate it if this was possible, but I guess that it's not a deal breaker for me - I'll still use this plugin because I managed to get it to do what I wanted in less than 15 minutes.

Thanks,
Amir

Sent from my iPhone

On 21 ביונ 2011, at 21:16, "t7mp" <reply@reply.github.com<mailto:reply@reply.github.com>> wrote:

Hi,
at the moment, this is not possible. But that is not a problem. A better approach could be to declare the version in the 'properties'-section and then use placeholders. Maybe:

<properties>
 <h2.version>1.3.155</h2.version>
</properties>

then do the following:

<dependecyManagement>
<dependencies>
<groupId>com.h2database</groupId>
<artifactId>h2</artifactId>
<version>${h2.version}</version>
</dependencies>
</dependencyManagement>

and

<plugin>
<groupId>com.googlecode.t7mp</groupId>
<artifactId>maven-t7-plugin</artifactId>
<configuration>
<libs>
<jarArtifact>
<groupId>com.h2database</groupId>
<artifactId>h2</artifactId>
<version>${h2.version}</version>
</jarArtifact>
</libs>
</configuration>
</plugin>

Doing it this way should work for you. It's a cleaner way, more maven-like, isn't it?

Jörg

##

**Comment by t7mp** [comment]
Hi Amir,

sorry, but for me it's not clear how your project setup looks like. Is it a normal multi-module-project or something different. Can you please make it clearer, a bit more visible (if possible) for me? Maybe we find a solution.

Cheers
Jörg

**Comment by amirkibbar** [comment]
Hi Jörg,

Here's an example for what I'm describing:

The imported pom:
<groupId>com.example</groupId>
<artifactId>something</artifactId>
<version>1.0</version>

<dependencyManagement>
<dependencies>
<dependency>
<groupId>com.h2database</groupId>
<artifactId>h2</artifactId>
<version>1.3.155</version>
</dependency>
</dependencies>
</dependencyManagement>

My parent pom:
...
<dependencyManagement>
<dependency>
<groupId>com.example</groupId>
<artifactId>something</artifactId>
<version>1.0</version>
<scope>import</scope>
</dependency>
</dependencyManagement>
...

The child pom (child of the parent pom, not the imported pom) can now define h2 without a version because its version was imported from the dependency management pom. Now there's no place to put a property with h2 version in it - if I put it in the parent pom it won't affect the dependency management pom, and if I put it in the dependency management pom then the property will not be available in the parent or child pom.

I hope this clears it up.

Thanks,
Amir

-----Original Message-----

**Comment by t7mp** [comment]
Hello,

thank you very much. I wasn't aware of a scope 'import' and so I never used it the last 5 years with maven. I had a look at the documentation and found out that this feature was available since 2.0.9. Incredible.

Ok, I think I will have an implementation ready until next weekend. But you have to use the 0.9.8-SNAPSHOT. Is that ok for you? So you will test all my refactorings by the way. And please, if you encounter any problems, bugs or whatever. Create an issue here.

Thank you.
Jörg

**Comment by amirkibbar** [comment]
That would be great, thank you!

-----Original Message-----

**Comment by marcobuss** [comment]
Also a thank you from me for pointing to the import scope

**Comment by t7mp** [comment]
Hi Amir,

please test it and report any issue you found and configure '<lookInside>true</lookInside>' to get more output to know what the plugin is doing.

Cheers

Jörg

**Comment by amirkibbar** [comment]
Sorry for the delay. Where can I get version 0.9.8-SNAPSHOT from?

-----Original Message-----

**Comment by amirkibbar** [comment]
Hi,

I built 0.9.8-SNAPSHOT locally and tried it, but it does not work. Here's the output:
[INFO] --- maven-t7-plugin:0.9.8-SNAPSHOT:run (start tomcat) @ mgmt-system-tests ---
[INFO]  [t7-lookInside] -- Fitler libs
[INFO]  [t7-lookInside] -- Filter webapps
[INFO]  [t7-lookInside] -- Artifact JarArtifact[com.h2database:h2:null:null:jar] has no version configured.
[INFO]  [t7-lookInside] -- artifacts without version found
[INFO]  [t7-lookInside] -- Project-Artifacts : 8
[INFO]  [t7-lookInside] -- found dependency : Dependency {groupId=junit, artifactId=junit, version=4.8.2, type=jar} groupId:junit artifactId:junit version:4.8.2 packaging:jar
[INFO]  [t7-lookInside] -- found dependency : Dependency {groupId=org.springframework, artifactId=spring-test, version=3.0.5.RELEASE, type=jar} groupId:org.springframework artifactId:spring-test version:3.0.5.RELEASE packaging:jar
[INFO]  [t7-lookInside] -- found dependency : Dependency {groupId=org.apache.httpcomponents, artifactId=httpclient, version=4.1.1, type=jar} groupId:org.apache.httpcomponents artifactId:httpclient version:4.1.1 packaging:jar
[INFO]  [t7-lookInside] -- found dependency : Dependency {groupId=org.springframework, artifactId=spring-webmvc, version=3.0.5.RELEASE, type=jar} groupId:org.springframework artifactId:spring-webmvc version:3.0.5.RELEASE packaging:jar
[INFO]  [t7-lookInside] -- found dependency : Dependency {groupId=javax.servlet, artifactId=servlet-api, version=2.5, type=jar} groupId:javax.servlet artifactId:servlet-api version:2.5 packaging:jar
[INFO]  [t7-lookInside] -- found dependency : Dependency {groupId=org.springframework, artifactId=spring-oxm, version=3.0.5.RELEASE, type=jar} groupId:org.springframework artifactId:spring-oxm version:3.0.5.RELEASE packaging:jar
[INFO]  [t7-lookInside] -- found dependency : Dependency {groupId=com.thoughtworks.xstream, artifactId=xstream, version=1.3.1, type=jar} groupId:com.thoughtworks.xstream artifactId:xstream version:1.3.1 packaging:jar
[INFO]  [t7-lookInside] -- found dependency : Dependency {groupId=org.apache.httpcomponents, artifactId=httpmime, version=4.0-alpha4, type=jar} groupId:org.apache.httpcomponents artifactId:httpmime version:4.0-alpha4 packaging:jar
[INFO]  [t7-lookInside] -- put key [com.h2database:h2:jar:null] to map for artifact [JarArtifact[com.h2database:h2:null:null:jar]]
[INFO]  [t7-lookInside] -- Filter projectArtifacts
[INFO]  [t7-lookInside] -- Search with key [junit:junit:jar:null] for artifact Dependency {groupId=junit, artifactId=junit, version=4.8.2, type=jar}
[INFO]  [t7-lookInside] -- Search with key [org.springframework:spring-test:jar:null] for artifact Dependency {groupId=org.springframework, artifactId=spring-test, version=3.0.5.RELEASE, type=jar}
[INFO]  [t7-lookInside] -- Search with key [org.apache.httpcomponents:httpclient:jar:null] for artifact Dependency {groupId=org.apache.httpcomponents, artifactId=httpclient, version=4.1.1, type=jar}
[INFO]  [t7-lookInside] -- Search with key [org.springframework:spring-webmvc:jar:null] for artifact Dependency {groupId=org.springframework, artifactId=spring-webmvc, version=3.0.5.RELEASE, type=jar}
[INFO]  [t7-lookInside] -- Search with key [javax.servlet:servlet-api:jar:null] for artifact Dependency {groupId=javax.servlet, artifactId=servlet-api, version=2.5, type=jar}
[INFO]  [t7-lookInside] -- Search with key [org.springframework:spring-oxm:jar:null] for artifact Dependency {groupId=org.springframework, artifactId=spring-oxm, version=3.0.5.RELEASE, type=jar}
[INFO]  [t7-lookInside] -- Search with key [com.thoughtworks.xstream:xstream:jar:null] for artifact Dependency {groupId=com.thoughtworks.xstream, artifactId=xstream, version=1.3.1, type=jar}
[INFO]  [t7-lookInside] -- Search with key [org.apache.httpcomponents:httpmime:jar:null] for artifact Dependency {groupId=org.apache.httpcomponents, artifactId=httpmime, version=4.0-alpha4, type=jar}
[INFO]  [t7-lookInside] -- 0 dependenciey applied
[INFO]  [t7-lookInside] -- check for noversion-artifacts again ...
[INFO]  [t7-lookInside] -- Artifact JarArtifact[com.h2database:h2:null:null:jar] has no version configured.
[INFO]  [t7-lookInside] -- Artifact JarArtifact[com.h2database:h2:null:null:jar] has no version configured.
[ERROR] No version configured for artifact --JarArtifact[com.h2database:h2:null:null:jar]

And here's my configuration (the relevant part):
<libs>
                        <jarArtifact>
                            <groupId>com.h2database</groupId>
                            <artifactId>h2</artifactId>
                        </jarArtifact>
</libs>

I was expecting the version to come from the dependency management of the parent poms, but it did not.

Thanks,
Amir

-----Original Message-----

**Comment by t7mp** [comment]
Hi Amir,

you can find snapshots in the Sonatype-OSS-Repository. Read the 'Getting Started' Section from the wiki.

I updated the sources to search for a valid version from dependencyManagement-Section too. So, we look into the normal dependencies and the managedDependencies. The projects dependencies will overwrite the managedDependencies section if there is an artifact with a version configured. Please check it again and provide your results in the comments. Thanks.

Joerg

**Comment by amirkibbar** [comment]
I built it locally and it work perfectly, thanks!

When do you think 0.9.8 will be released?

Thanks,
Amir

-----Original Message-----

**Comment by t7mp** [comment]
Hello Amir,

great to heare it works.
Thanks for testing. 0.9.8.M1 was released 5 min ago and should be available from maven central in a few hours.

Cheers
Jörg
