### ISSUE TITLE
support for classifier in the war identification

### ISSUE THREAD

**Issue by amirkibbar** [t7mp/t7mp#18]
hi,

(sorry to be a nag) as part of my integration test I instrument my web application with cobertura as part of my webapp project. the result is that my webapp project has 2 artifacts - the regular war file and an instrumented war file. The instrumented war has a classifier "cobertura".

However, the t7mp plugin does not support the classifier property in the webappArtifact section - it simply ignores it, which means that during my integration tests i cannot use the instrumented war.

Here's how I'd expect the webappArtifact to be defined:

```
                    <webappArtifact>
                        <groupId>${project.groupId}</groupId>
                        <artifactId>my-webapp</artifactId>
                        <classifier>cobertura</classifier>
                        <version>${project.version}</version>
                        <contextPath>my-webapp</contextPath>
                    </webappArtifact>
```

I'd be happy to test this when you have a solution (you will have a solution, right?), but please tell me how to get the snapshot version, or should i just build it locally myself?

thanks,
Amir

**Comment by marcobuss** [comment]
I have fixed the Issue. Please check if it works as espected.

Currently the version can´t be found at Sonatype Nexus. Please wait until it can be found in the repository or build it by your own.

Cheers

Marco

**Comment by amirkibbar** [comment]
Hi,

I built it locally and tried it - the classifier works!

Thanks for the very quick response,
Amir

-----Original Message-----
