### ISSUE TITLE
Debugging application running in the t7mp's Tomcat

### ISSUE THREAD

**Issue by amirkibbar** [t7mp/t7mp#25]
hi,

is it possible to start the tomcat in the plugin in debug mode, i.e. with the following parameters:
 -agentlib:jdwp=transport=%JPDA_TRANSPORT%,             address=%JPDA_ADDRESS%,server=y,suspend=%JPDA_SUSPEND%

thanks,
Amir

**Comment by marcobuss** [comment]
that ist realy simple.

use mvndebug t7:run. With mvndebug you can debug all maven processes.

**Comment by amirkibbar** [comment]
Thanks, I will try it

-----Original Message-----

**Comment by amirkibbar** [comment]
mvndebug is a good workaround
