### ISSUE TITLE
t7 plugin attempts to download my dependencies from the web

### ISSUE THREAD

**Issue by amirkibbar** [t7mp/t7mp#31]
hi,

I've added a dependency that is created during my build to the <libs> section of the t7 plugin configuration. When I use t7:run then the plugin attempts to download my dependency from tomcat.apache.org and people.apache.org - it obviously does not exist there, so it fails and continues normally, but this downloading and failing takes relativly long time. Is there a way to disable this behavior?

here's the output from the execution

Downloading: http://tomcat.apache.org/dev/dist/m2-repository/<my-artifact-identification>/maven-metadata.xml
Downloading: http://people.apache.org/repo/m2-snapshot-repository/<my-artifact-identification>/maven-metadata.xml
[WARNING] Could not transfer metadata <my-artifact-identification>/maven-metadata.xml from/to t7mp.apache.tomcat.dev (http://tomcat.apache.org/dev/dist/m2-repository): Error transferring file: Connection timed out: connect

the connection is timed out because my network requires a proxy to get to the internet which i didn't define for maven, but this is not the problem - since the metadata for my artifact will never be in the tomcat/people apache.org site.

thanks,
Amir

**Comment by t7mp** [comment]
Hi Amir,

I removed these two extra repositories. So only the repositories configure in the pom.xml will be used.
Hope that resolve this Issue. Please try it again and let us know when you can resolve the dependencies you need.

Cheers
Jörg

**Comment by amirkibbar** [comment]
Hi Jörg,

I've downloaded t7 sources, compiled locally and tried to use it without changing anything in my project (except the version of the t7 plugin). I now get the following error:

[ERROR] Could not find artifact com.googlecode.t7mp:tomcat:zip:7.0.19-SNAPSHOT

Try downloading the file manually from the project website.

Then, install it using the command:
    mvn install:install-file -DgroupId=com.googlecode.t7mp -DartifactId=tomcat -Dversion=7.0.19-SNAPSHOT -Dpackaging=zip -Dfile=/path/to/file

Alternatively, if you host your own repository you can deploy the file there:
    mvn deploy:deploy-file -DgroupId=com.googlecode.t7mp -DartifactId=tomcat -Dversion=7.0.19-SNAPSHOT -Dpackaging=zip -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  com.googlecode.t7mp:tomcat:zip:7.0.19-SNAPSHOT

I assume that this dependency is available somewhere in your m2 repo, but I don't know which repo to use.

thanks,
Amir

**Comment by amirkibbar** [comment]
Hi,

as a temporary workaround I've added the following to my settings.xml to disable these repositories:
 <profiles>
                <profile>
                        <id>disable-unneeded-repos</id>
                        <activation>
                                <activeByDefault>true</activeByDefault>
                        </activation>
                        <repositories>
                                <repository>
                                        <id>apache-snapshots</id>
                                        <url>http://people.apache.org/repo/m2-snapshot-repository\</url\>
                                        <releases>
                                                <enabled>false</enabled>
                                        </releases>
                                        <snapshots>
                                                <enabled>false</enabled>
                                        </snapshots>
                                </repository>
                                <repository>
                                        <id>powermock-repo</id>
                                        <url>http://powermock.googlecode.com/svn/repo\</url\>
                                        <releases>
                                                <enabled>false</enabled>
                                        </releases>
                                        <snapshots>
                                                <enabled>false</enabled>
                                        </snapshots>
                                </repository>
                                <repository>
                                        <id>codehaus.snapshots</id>
                                        <url>http://snapshots.repository.codehaus.org\</url\>
                                        <releases>
                                                <enabled>false</enabled>
                                        </releases>
                                        <snapshots>
                                                <enabled>false</enabled>
                                        </snapshots>
                                </repository>
                        </repositories>
                </profile>
        </profiles>

**Comment by t7mp** [comment]
Hi Amir,

thank you for testing and sorry for the issues you had. It seems that I missed a very important step, to release the tomcat-zip.
I will do that this evening when I'm at home.
If you can't wait please at the following repository to your pom as in this pom.xml:

https://github.com/t7mp/t7mp/blob/master/src/it/7.0.19-background/pom.xml

Then you should find the needed zip-File to install.

Cheers
Jörg

**Comment by t7mp** [comment]
Hi Amir,

as written in the comment before I tried to upload the needed artifacts to sonatypes oss staging repository. But when I tried to close the repository (what is necessary to release the artifact) I got error messages. I raised an Issue to the OSS-repository admin.
But to solve the problems for you and other that want to try/use the plugin I created an maven repository at github. This should work I had no errors with the integration tests.
So please try again. Remove your workaround before ;-)

If this work, please close the issue. Thanks.

Cheers
Jörg
