### ISSUE TITLE
plugin configuration ignores properties from parent pom

### ISSUE THREAD

**Issue by akutschera** [t7mp/t7mp#35]
When I configure the t7-plugin in a parent pom and set some properties, e.g.
<systemProperty>
                  <key>t7.port</key>
                  <value>${dynamic.random.port}</value>
</systemProperty>

these properties are not available in a child pom when I set some different properties in the child pom.

Workaround is setting all systemProperties in the child pom. Preferred is setting them in the parent pom and adding / overwriting them in the child pom.

**Comment by jbellmann** [comment]
Hi Andreas,

I can not reproduce this issue. I added an integration-test under 'src/it/inheritConfiguration'. There I configured the 'tomcatHttpPort' with a value 9090 and 'tomcatVersion' with a value 7.0.14. In the 'submodule' I didn't reconfigure these properties. Only 2 different properties. As you will see the port used when tomcat starts is the 9090 as configured in parent-pom.

Please checkout the project and start a full build including integration tests with : mvn clean install -Prun-its

What are your results? If I got something wrong, please provide a new configuration for an integration test.

Cheers,
Jörg

**Comment by marcobuss** [comment]
Add Exmple to show inheritance

https://github.com/marcobuss/examples/commit/acef9a212358ca7355e23329896f4d4aea80e343

so all works as expected I close the Issue
