### ISSUE TITLE
t7mp 0.9.8.M2A downloads tomcat from github

### ISSUE THREAD

**Issue by amirkibbar** [t7mp/t7mp#37]
hi,

t7mp 0.9.8.M2A attempts to download the tomcat-7.0.21.zip directly from github, ignoring my mirror definitions in my settings.xml.

I can only work through an internal m2 repo (nexus) - so this direct download causes me a serious problem.

here's the log from my build:

[INFO] --- maven-t7-plugin:0.9.8.M2A:run (start tomcat) @ mgmt-system-tests ---
Downloading: https://github.com/t7mp/t7mp.maven.repo/raw/master/releases/com/googlecode/t7mp/tomcat/7.0.21/tomcat-7.0.21.zip
[ERROR] Could not transfer artifact com.googlecode.t7mp:tomcat:zip:7.0.21 from/to t7mp.maven.repo.releases (https://github.com/t7mp/t7mp.maven.repo/raw/master/releases): Error transferring file: Connection timed out: connect
  com.googlecode.t7mp:tomcat:zip:7.0.21

from the specified remote repositories:
  apache-snapshots (http://people.apache.org/repo/m2-snapshot-repository, releases=false, snapshots=false),
  powermock-repo (http://powermock.googlecode.com/svn/repo, releases=false, snapshots=false),
  codehaus.snapshots (http://snapshots.repository.codehaus.org, releases=false, snapshots=false),
  oo-nexus (http://mydtbld0001.isr.hp.com:8081/nexus/content/groups/oo-public, releases=true, snapshots=false),
  t7mp.maven.repo.releases (https://github.com/t7mp/t7mp.maven.repo/raw/master/releases, releases=true, snapshots=false)

org.apache.maven.plugin.MojoExecutionException: Could not transfer artifact com.googlecode.t7mp:tomcat:zip:7.0.21 from/to t7mp.maven.repo.releases (https://github.com/t7mp/t7mp.maven.repo/raw/master/releases): Error transferring file: Connection timed out: connect
  com.googlecode.t7mp:tomcat:zip:7.0.21

with 0.9.8.M1 everything is fine (it downloads different artifacts though).

thanks,
Amir

**Comment by jbellmann** [comment]
Hi Amir,

you are right, the plugin adds our repo. I had some issues on the sonatype-oss-repository and raised an issues (https://issues.sonatype.org/browse/OSSRH-2115 ). So I tried to provide an repo on github. And normally it works good.

When you can only work through an nexus ( I guess : 'oo-nexus' ?), then why do you have configured 'apache-snapshots', 'powermock-repo' and 'codehaus.snapshots' as repositories to lookup? 

The error-message says: Connection timed out. Maybe there was an problem on github to process the request. Please could you try out to download the artifact with the link in your message with an browser? When I click the link I got the artifact.

Or, as a workaround when it is really impossible for you to download it in the build, add the repo to your nexus and to the 'oo-public' group. Does this help?

The issue on sonatype-oss I mentioned above was fixed some days later. So I will try again to upload the tomcat-zips to 'maven-central'. If I get it working, I will remove the additional github-repository. And hopefully this fixes your problems.
You have to make sure you add 'central' to your nexus-public-group.

Cheers,
Jörg

**Comment by amirkibbar** [comment]
Hi Jörg,

oo-nexus is our internal central repository. In its public group I've added the github repository, but still the t7mp tries to go directly to the github repository ignoring my settings.

The connection timed out because my network requires a proxy to go to the internet, which I haven't setup - only my nexus is setup with the proxy and is actually allowed outside.

The other repositories you see in the log (apache-snapshots, etc.) were added because of a previous similar bug in t7mp - but all of them are actually disabled in my settings.

Thanks,
Amir

-----Original Message-----

**Comment by jbellmann** [comment]
Hi Amir,

all versions of Tomcat supported by t7mp (6.0.24 - 6.0.33, 7.0.6 - 7.0.21) are now available on maven-central (http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.googlecode.t7mp%22%20AND%20a%3A%22tomcat%22).
Please try again to resolve the needed artifacts with the '-U' parameter for 'Update' (mvn clean install -U).

Time was to short to remove the added repo in the code and test all that. But we will have a release (0.9.8) this week. And I will do all the things necessary for this issue. So if it does not work with artifacts in maven-central you have to wait until next week.

Cheers,
Jörg

**Comment by amirkibbar** [comment]
Hi,

Thank you - this resolved the problem.

Thanks,
Amir

-----Original Message-----
