### ISSUE TITLE
Create a goal for inplace deployment

### ISSUE THREAD

**Issue by marcobuss** [t7mp/t7mp#4]
MOVED FROM GOOGLECODE:

Reported by michel.barret, Jan 19, 2011

Hello,

Can it possible to have a inplace target to speed up deployment ?

---

Comment 1 by project member joerg.bellmann, Feb 03, 2011

Hi Michel,
can you please describe with some words what you mean with 'inplace target'.
How do you think, we can speed up the deployment?

Thanks

---

Comment 2 by michel.barret, Feb 03, 2011

Thanks for your answer.

I think a goals as "mvn t7:inplace".

The methode permit to tomcat deploy an webapp without build a war file. Maven build the class file in target directory and the other ressources (as servlet or jsp by example) are directly keep in src\main\webapp.

With this methode isn't necessary redeploy when we modify the ressources files (*.htmls, *.css, *.jsp,...).

---

Comment 3 by aliksa...@gmail.com, Feb 04, 2011

Hi! This plugin is cool, been using it on our tomcat7 project.

I think of this in-place goal as the way jetty-plugin does:
http://jetty.codehaus.org/jetty/maven-plugin/run-mojo.html

This would be awesome if implemented to behave like so, any change in classes or resources triggers server redeploy/restart, and tomcat7 being ultra-fast restarting it should really speed up anyone's development.

**Comment by t7mp** [comment]
Is this obsolet with the scanner?

**Comment by t7mp** [comment]
Hi marco,

as in the comment above, is this obsolet?

MfG
Jörg

**Comment by marcobuss** [comment]
I think so.
- CLOSED -
