### ISSUE TITLE
Version 0.9.8 has not been published on maven central repository

### ISSUE THREAD

**Issue by noirbizarre** [t7mp/t7mp#41]
I saw you released the version 0.9.8 but I can't finf it on maven central repository:

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.googlecode.t7mp%22%20AND%20a%3A%22maven-t7-plugin%22%20AND%20v%3A%220.9.8%22

**Comment by jbellmann** [comment]
Ok,
I will verify that when I'm at home this evening.
I could swear that I hit the 'release'-button on oss-sonatype-nexus. ;-)

Jörg

**Comment by jbellmann** [comment]
Hi,

the artifact was in a staging repository. Maybe I was a bit confused on the release day ;-). But I did all needed steps to release it and got mails now.

<code>
Description:

release it

Details:

The following artifacts have been promoted to the Releases repository.

archetype-catalog.xml
maven-t7-plugin-0.9.8-javadoc.jar
maven-t7-plugin-0.9.8.jar.asc
maven-t7-plugin-0.9.8-javadoc.jar.asc
maven-t7-plugin-0.9.8-sources.jar
maven-t7-plugin-0.9.8.pom
maven-t7-plugin-0.9.8.pom.asc
maven-t7-plugin-0.9.8.jar
maven-t7-plugin-0.9.8-sources.jar.asc
</code>

It needs some hours to synch the repositories but tomorow it should be available on maven-central.

Cheers
Jörg

**Comment by noirbizarre** [comment]
Thanks for the reactivity!!
