### ISSUE TITLE
Support to change context path

### ISSUE THREAD

**Issue by ksangani** [t7mp/t7mp#45]
Add support to change context path for the war project. By default it deploys under ${project.build.finalName} context. Similar feature is available in tomcat-maven-plugin (http://mojo.codehaus.org/tomcat-maven-plugin-parent/tomcat-maven-plugin/run-mojo.html#path)

**Comment by jbellmann** [comment]
Hi ksangani,

it is supported. ;-)
Please add 

```
<contextPath>whatContextPathYouWant</contextPath>
```

 in the confiugration-section of the plugin.
For all available configuration-elements see : http://t7mp.github.com/docu/html/ch01.html

Please comment and close the issue if this was what you are looking for.

Cheers
Jörg

**Comment by ksangani** [comment]
Yes version 0.9.8 has the support.

**Comment by jbellmann** [comment]
Ksangani,

latest version is 0.9.9.M1, maybe you can try/test that version.

You are welcome

Jörg
