### ISSUE TITLE
plugin should provide an opportunity to use a maven artifact for tomcat configuration

### ISSUE THREAD

**Issue by marcobuss** [t7mp/t7mp#46]
With the plugin it should be be possible to define an Artifact as an "configuration artifact". 
The plugin must unpack the artifact and copy the entire content in the tomcat conf directory.

That would be realy helpfull when you have a bunch of projects wich all need the same configuration. If a change is required you only have to change the configuration once.

The configuration can lock somethin like this:

&lt;libs&gt;
  &lt;configArtifact&gt;
    &lt;groupId&gt;your.groupid&lt;/groupId&gt;
    &lt;artifactId&gt;your.configuration.artifact&lt;/artifactId&gt;
    &lt;version&gt;1.0&lt;/version&gt;
  &lt;/configArtifact&gt;
  &lt;jarArtifact&gt;
    &lt;groupId&gt;org.apache.activemq&lt;/groupId&gt;
    &lt;artifactId&gt;activemq-core&lt;/artifactId&gt;
    &lt;version&gt;5.4.0&lt;/version&gt;
  &lt;/jarArtifact&gt;
&lt;/libs&gt;

**Comment by jbellmann** [comment]
Hey Marco,

no problem, interesting point. You can start with the implementation on a separat branch. Let me see what you want to do and how do you want to do that.

We will see us on thursday? Gradle-Event?

MfG
Jörg

**Comment by jbellmann** [comment]
Hello Marco,

try the branch 'feature/configurationArtifact'. Maybe this is what you need ;-)

MfG
Jörg

**Comment by jbellmann** [comment]
Hi Marco,

can you please review the implementation?

Cheers
Jörg

Merry Christmas.

**Comment by marcobuss** [comment]
Happy new year Jörg,

i have testet the implementation. In general it works but I´am not sure if the last position is best for the step.

If we let it in the last position we must document exactly that it is not an good idea to put catalina.properties or other files that came with the plugin in the config artifact.

**Comment by jbellmann** [comment]
Hi marco,

you asked last week via mail. Does it work like expected? Can you close the issue then?

Cheers
Jörg

**Comment by marcobuss** [comment]
Sorry, verry busy the last time. 

I´ll give it a try the next weekend. Changing plugin version during the sprint is not the best Idea.

**Comment by marcobuss** [comment]
Works like a charm.
- Example will follow

Thx.
