### ISSUE TITLE
mvn t7:run execution issue through java

### ISSUE THREAD

**Issue by zarub2k** [t7mp/t7mp#47]
Hi,
I am trying to execute the above command through java Runtime process. But it is not completing its execution. I am always getting "server starting" message. After that the execution is not passed over.

Any clue to fix this issue?

Thanks,
Tham

**Comment by jbellmann** [comment]
Hi Tham,

sorry, but I don't really understand what you are doing or trying. " ... through java Runtime process". Can you please explain in more detail what you are doing or how do you use the plugin.

Cheers
Jörg

**Comment by zarub2k** [comment]
Hi Jorg,
Sorry for NOT giving much information about the problem. What I am trying here is, I have a pom which is having the t7 start and stop functionality. This will automatically start my war file. I have integrated this with my own java client. So I am trying to execute this with my client code. Whenever I call "mvn t7:run" through my java code using Runtime instance, I am able to see some logs till "Server starting..." After that nothing is happened.

But whenever I try this directly in the command window, I am able to start my server and able to hit the server. Could you give me some hint?

Thanks,
Tham

**Comment by jbellmann** [comment]
Hi Tham,

I still don't have any idea WHY you are doing this. Do you want to integrate Tomcat in your own application? Then there should be another way to do that. Then you can have a look at: 

https://github.com/t7mp/t7mp/blob/master/src/main/java/com/googlecode/t7mp/RunForkedMojo.java

There I tried to run a Tomcat-Instance in an forked process via Runtime. Maybe you find some answers there.

But there are also other ways to embedding Tomcat 7. See here: http://www.copperykeenclaws.com/embedding-tomcat-7/
Or if you need other examples or App-Server you can try Jetty too. It is often used for such scenario.

But I think this is not an issue of t7mp. So I close this issue.

Feel free to ask further questions on our discussion-group: https://groups.google.com/forum/?hl=en#!forum/t7mp
Whenever I can help, I will do that.

Regards,
Jörg

**Comment by zarub2k** [comment]
Hi Jorg,
To get a clear understanding I am sharing my pom and my console output here. Through java file I am trying to execute the pom.xml to start the tomcat. The following are my code snippets,

Java file:
File file = new File("<pom_dir>");

```
    List<String> commands = new ArrayList<String>();
    commands.add("cmd");
    commands.add("/c");
    commands.add("mvn");
    commands.add("t7:run");

    ProcessBuilder processBuilder = new ProcessBuilder(commands);
    processBuilder.directory(file);

    Process process = processBuilder.start();
```

pom.xml:
<build> 
        <finalName>ci</finalName>
        <plugins>
            <plugin>
                    <groupId>com.googlecode.t7mp</groupId>
                    <artifactId>maven-t7-plugin</artifactId>
                    <version>0.9.6</version>
                    <configuration>
                        <tomcatHttpPort>3579</tomcatHttpPort>
                        <tomcatShutdownPort>3005</tomcatShutdownPort>
                        <tomcatShutdownCommand>SHUTDOWN</tomcatShutdownCommand>
                        <tomcatVersion>7.0.6</tomcatVersion>
                        <tomcatSetAwait>true</tomcatSetAwait>
                    </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>2.3</version>
          </plugin>
        </plugins>
    </build>

Console output:

[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building CI Web Application 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-t7-plugin:0.9.6:run (default-cli) @ ci ---
[WARNING] The configured Directory for configuration files does not exist. C:\download\workspace\tools\jenkins\src\main\tomcat\conf
[WARNING] Ignoring user configuration.
[INFO] Starting Tomcat ...

---

After the starting tomcat I am not able to get anything from my console. And I was not able to access my webapp. But at the same time If i run the same command through command line i was able to start the tomcat successfully and was able to access my app.

Thanks,
Tham

**Comment by jbellmann** [comment]
Hey Tham,

thanks for the code. But you did not explain WHY ARE YOU DOING THIS. But because of 'jenkins' in your output and 'ci' as the finalName, do you try to run some integration tests for your webapp? Then there are other ways doing that.
So please, explain WHY ARE YOU DOING THIS!

I don't have the time to solve your problems. You can ask questions. But as in my comment above, use the discussion group please. I will answer further questions there.

Cheers
Jörg
