### ISSUE TITLE
mvn t7:run-forked error

### ISSUE THREAD

**Issue by zarub2k** [t7mp/t7mp#48]
Hi,
<plugin>
                    <groupId>com.googlecode.t7mp</groupId>
                    <artifactId>maven-t7-plugin</artifactId>
                    <version>0.9.8</version>
                    <configuration>
                        <tomcatHttpPort>3579</tomcatHttpPort>
                        <tomcatShutdownPort>3005</tomcatShutdownPort>
                        <tomcatShutdownCommand>SHUTDOWN</tomcatShutdownCommand>
                        <tomcatVersion>7.0.8</tomcatVersion>
                        <tomcatSetAwait>true</tomcatSetAwait>
                    </configuration>
            </plugin>

The above is my pom configuration. If I try to execute mvn t7:run-forked
I am getting the following exception,
[ERROR] Cannot run program "catalina.bat" (in directory "<POM_DIR>\target\tomcat\bin"): CreateProcess error=2, The system cannot find the file specified.

How to resolve this error?

Thanks,
Tham

**Comment by zarub2k** [comment]
I forgot to mention one thing. I manually check the folder mentioned in the error. I found the catalina.bat file and I was able to manually execute the catalina.bat command with "catalina.bat run" .

Thanks,
Tham

**Comment by jbellmann** [comment]
Hi Tham,

can you please retest with the latest release 0.9.9.M1 and let me know if you can reproduce this error? My problem is that I don't have an windows os running on any of my machines. I have to prepare an VM first. So it can take a while.

Thanks,
Jörg

**Comment by jbellmann** [comment]
Hi Tham,

I reproduced this error. I will try to fix this issue as fast as possible.

Cheers
Jörg

**Comment by jbellmann** [comment]
Hi Tham,

should be fixed with latest SNAPSHOT. You can try this with the examples-project: https://jbellmann@github.com/t7mp/examples.git

Cheers,
Jörg

Merry Christmas

**Comment by jbellmann** [comment]
I will publish a new milestone release with this fix and the development for #46 after 26.12.2011 to maven-central.

**Comment by zarub2k** [comment]
Hi Jorg,
Thanks for the fix. Have you already pushed your changes into M1 branch. I tried today, still I am not able to run the command successfully.

Thanks,
Tham

**Comment by jbellmann** [comment]
Hi Tham,

please use 0.9.9 (no snapshot, no milestone). Should be available in maven-central tomorrow.

Cheers
Jörg

**Comment by zarub2k** [comment]
Hi Jorg,
Thanks for the fix. Now I am able to run t7:run-forked successfully through my java client. Once again thanks for your fix.

Thanks,
Tham
