### ISSUE TITLE
Support setting system-properties in plugin configuration

### ISSUE THREAD

**Issue by marcobuss** [t7mp/t7mp#5]
MOVED FROM GOOGLECODE:

Reported by project member joerg.bellmann, Jan 20, 2011

It should be possible to define some system-properties in the configuration-section of the plugin.

---

Comment 1 by project member joerg.bellmann, Today (11 hours ago)

${catalina.home}, ${catalina.home} should be resolved to

**Comment by t7mp** [comment]
To find in 0.9.7-SNAPSHOT.
