### ISSUE TITLE
how to set JVM options?

### ISSUE THREAD

**Issue by rmannibucau** [t7mp/t7mp#51]
It could be nice if setting custom jvm option was supported (as system properties is)

For instance -Xdebug or -javaagent is currently not supported.

**Comment by jbellmann** [comment]
Hi,

you can have a look at our examples:

https://github.com/t7mp/examples/tree/master/simple/src/main/tomcat/bin

You will find a 'setenv.sh' where you can set such options in the default 'tomcat-way'. Run the tomcat-instance in forked mode with 'mvn t7:run-forked'.

Please make sure you use the last released version (0.9.9) or the latest SNAPSHOT ( 0.9.10-SNAPSHOT) if you try this on a windows machine.

Please let us know if you have other issues with the plugin or some feature requests.

Cheers
Jörg

**Comment by jbellmann** [comment]
If you just want to debug you application, try mvnDebug t7:run instead of mvn t7:run. So the whole maven process runs in debug-mode and it should respect your Debug breakpoints.

You are welcome

**Comment by rmannibucau** [comment]
setenv.sh is great.

Thank you!
