### ISSUE TITLE
Use something based on tomcat

### ISSUE THREAD

**Issue by rmannibucau** [t7mp/t7mp#52]
Apache TomEE (for instance) is based on tomcat but can't be used directly with t7 plugin.

If a kind of default config can be provided it could be extended.

What i think of is something like:
-> the plugin brings a config file with the following info
    1. alias/name
    2. assembly/artifacts to download (link or maven dep)
    3. a "runner" implementation
    4. other conf (in fact all the options which can be specified in the plugin configiration)

All the magic should be in the runner which will run by reflection the good starting class

Any thought about it?

In the conf the alias can be added and wrap more conf.

**Comment by jbellmann** [comment]
Hi,

should be possible. It's the same way the plugin works now. But I don't have any experiences with TomEE yet. I will have a look at it.
So I will think about that and will see what I can do in my spare time. ;-)
Also you can provide some code on a fork if you want.

Thanks for sharing your thoughts.

Jörg

**Comment by rmannibucau** [comment]
Today to use tomee what we do is adding the tomee webapp but that's because tomee is able to get rid of the whole application for some cases.

The real assembly (same tomcat layout) is found here http://repo1.maven.org/maven2/org/apache/openejb/apache-tomee/<version>

There are 2 versions:
1. webprofile
2. plus

both of them are classifier (so it should be easy to manage it in a pojo).

What i don't know if how to say the source if the "tomcat base" with t7.

Another point is catalina.sh and .bat are a bit customized with tomee.

**Comment by jbellmann** [comment]
Hi,

I did some testing and got it running. You can have a look at our examples project:

https://github.com/t7mp/examples

In the submodule 'tomee' you will find and an working example that uses the 'webprofile'. At the moment it is only running in forked mode. But I'm sure we can get it running in process too.

Cheers
Jörg

**Comment by rmannibucau** [comment]
the issue with this example is you add librairies to the tomcat which is clearly what tomee tries to avoid (lib + some specific config).

trying your example i have: 

```
[INFO]  [t7-lookInside] -- 
[INFO]  [t7-lookInside] -- 
[ERROR]     [t7-lookInside] -- ======================= MAVEN-T7-PLUGIN ==================
[ERROR]     [t7-lookInside] -- This plugin supports only Version 7 or 6 of Tomcat. You configured: 1.0.0-beta-1. Cancel the     Build.
[ERROR]     [t7-lookInside] -- ===========================================================
[INFO]  [t7-lookInside] -- 
[INFO]  [t7-lookInside] --
```

because of this check: https://github.com/t7mp/t7mp/blob/master/src/main/java/com/googlecode/t7mp/PreConditions.java

What don't you simply download and extract the zip? TomEE preconfigured package is deployed on repo1 so it is easier than tomcat to download i guess.

**Comment by jbellmann** [comment]
Do you run it as explained in the examples readme? Do you use it with 'mvn t7:run-forked-tomee' ? As you can see here

https://github.com/t7mp/t7mp/blob/develop/src/main/java/com/googlecode/t7mp/TomeeRunForkedMojo.java
(develop branch)
the 'Preconditions' was commented.
I came to this issue too and disabled the 'versionCheck'. Please see the examples again.
Be aware, that is a first implementation/possible way to support your needs. It can be that it is buggy and you will find more issues. Please report your problems.

And yes I know that I only have to download and extract the zip. That's what I'm doing in this solution.

If you think you don't need the libraries I added (you mean javax.ejb, openjpa, right) all I can tell you is that I got NoClassDefFoundExceptions when I was starting the TomEE without that libraries. Do I have to run another script than 'catalina.sh' ?

Cheers
Jörg

**Comment by rmannibucau** [comment]
Opps, sorry, skipped this goal :s

i think default configuration files copied from CopyConfigResourceFromClasspath steps should be removed.

A rule like if file already exists, skip it can be enough.

Any thought about it?

**Comment by marcobuss** [comment]
Hi all,

after a few days thinking about this issue i came to the point that it is not a good idea to support the TomEE native. I think a dedicated plugin would be a better solution. 

The main fact is that we break the "Single Responsibility" principle. The intenton for this plugin was to support Tomcat 7 in maven builds. My point of view is that TomEE is "NOT" Tomcat it is a server "based" on Tomcat.
A few Application Server also uses Tomcat as webserver. Does that mean it is a good idea to support this servers? I don´t thinks so.
No user expected that a maven plugin with the name "maven t7 plugin" supports TomEE so i think we should follwo the name an only support plain Tomcat.
Another point is that it blows up the configuration. I fear that we have potentialy parts that are specific for TomEE. I like a simple Plugin with an focused usecase and not an plugin you can do plenty of things.

We can put an example in the example project wich demonstrate how to use t7mp with the TomEE-Webapp but please no native support.

**Comment by rmannibucau** [comment]
i thought of it too and i still think it can be merged since it is almost the same thing: simply extract tomee + override conf if user provided such a file and that's all no?

all is missing to support such servers is 1) define the "tomcat base" as a maven dependency, 2) not overwrite conf file when it exists

you think it is too much? the default case is just a kind of default no?

**Comment by dblevins** [comment]
We'd be happy to maintain a version of the plugin that is focused on TomEE.  To do that, we'd just need permission to copy the code over to Apache in the form of a CLA http://apache.org/licenses/icla.pdf  (all apache committers and contributors have one on file)

Would be stellar to have a TomEE version of this excellent plugin maintained by the TomEE community.

**Comment by marcobuss** [comment]
it is right that supporting TomEE is no big deal. But make a new plugin based on t7mp focused on TomEE is a much cleaner solution for me.

So the new Plugin can be maintained by the TomEE Community to get better support for features only TomEE needs.

For me a copy of my work is ok when the new Plugin offers a link to t7mp on his website but Jörg is the Founder and main contributer so we must see what he thinks about it.

**Comment by jbellmann** [comment]
Hi all,

you all are right, running TomEE with the 'maven-t7-plugin' is simple. And if I can help to make development with TomEE easier I will do it. With Marco's comment in mind I split the code in three parts (and repositories).

[maven-t7-common](https://github.com/t7mp/maven-t7-common) will host the most code that was available before and will be a shared artifact for [maven-t7-plugin](https://github.com/t7mp/maven-t7-plugin) and [maven-tomee-plugin](https://github.com/t7mp/maven-tomee-plugin).

Is this a way we can go for the next weeks or months?

Cheers
Jörg

**Comment by jbellmann** [comment]
Hi David, hi rmannibucau

I saw there is some ongoing development on a tommee-maven-plugin by rmannibucau in the openejb-repository at apache.org. So what are your interests here? Grab the code to get your plugin up and running or do you want to invest in development of the existing codebase here? And what should be my part for further development?

Please don't misunderstand my question. Maybe it sounds a bit harsh. But my english is not good and maybe it sounds harder than it was meant.

Cheers
Jörg

**Comment by dblevins** [comment]
On Jan 26, 2012, at 1:10 PM, Jörg Bellmann wrote:

> Hi David, hi rmannibucau
> 
> I saw there is some ongoing development on a tommee-maven-plugin by rmannibucau in the openejb-repository at apache.org. So what are your interests here? Grab the code to get your plugin up and running or do you want to invest in development of the existing codebase here? And what should be my part for further development?
> 
> Please don't misunderstand my question. Maybe it sounds a bit harsh. But my english is not good and maybe it sounds harder than it was meant.

No worries.  Any of the above sounds fine to me.  I personally think it's a bit of a shame Tomcat themselves haven't encouraged you to join Tomcat and have the work be done right there in Tomcat and promote it to all the Tomcat users.

We're a very open community and if you wanted to work on the plugin right at Apache I think there'd be a lot of people in the TomEE community who'd be very excited.  Both Tomcat and TomEE versions would fit right in.

Any thoughts?

-David

**Comment by rmannibucau** [comment]
the tomee plugin does a bit more than t7 plugin can do but the tomee philosophy is "use tomcat tools" so t7 should work fine too.

As David said there is place for you @ apache too ;)

**Comment by jbellmann** [comment]
Ok,

I will think about your offer. Thank you.

Btw. I released a new milestone (0.9.10.M2) for the [maven-tomee-plugin](https://github.com/t7mp/maven-tomee-plugin). You are now able to configure the 'distribution' (webprofile or plus) and the 'version' (defaults to the latest release 1.0.0-beta-2).

Cheers
Jörg

**Comment by rmannibucau** [comment]
well if you fork for tomee i guess you should try to avoid to force to add spec jars, no?

maybe we can merge our both plugins?

**Comment by jbellmann** [comment]
Your are right, I fixed this.

Cheers
Jörg

**Comment by jbellmann** [comment]
Hi Romain, David

I had a look to the implementation of your TomEE-Plugin and it looks very good. Didn't tried it but looks familiar ;-)
I was impressed that Romain got it all in nearly one class. Well done. I think for maintenance or new developers it fits better than mine.
So I really think about to rewrite 'maven-t7-plugin' to use the same 'style' if you allow me to do that and if I got it working without skipping any existent feature.
Let me hear what you are thinking about that.

If you are still interested in merging or sharing some code I'm willing to do so. When I can support you on the plugin (where there any tests ? ;-)  )  tell me what I have to do to become a 'committer'.

Cheers
Jörg

**Comment by rmannibucau** [comment]
Hi Jörg,

since the code is under Apache licence do what you want ;)

i think merging both (=taking part of yours and part of tomee one) can make a really good plugin.

to become a committer you need to participate to the life of openejb/tomee (that's the way Apache works). It can start posting on the mailing list and little things like that.

What i don't know is how to keep tomee plugin functionnalities since now we added specific features (listing ejbs for instance).
