### ISSUE TITLE
libs should support <scope>, <systemPath> for local jars

### ISSUE THREAD

**Issue by russt** [t7mp/t7mp#53]
would be nice if &lt;lib&gt; configuration element supported local jars, i.e.,

&lt;libs&gt;
   &lt;jarArtifact&gt;
       &lt;groupId&gt;com.bar&lt;/groupId&gt;
        &lt;version&gt;1.0&lt;/version&gt;
        &lt;scope&gt;system&lt;/scope&gt;
        &lt;artifactId&gt;foo&lt;/artifactId&gt;
        &lt;systemPath&gt;/tmp/foo.jar&lt;/systemPath&gt;
    &lt;/jarArtifact&gt;
&lt;/libs&gt;

workaround is to install local jars in m2/repository.

**Comment by jbellmann** [comment]
Hi russt,

should not be so difficult to implement. Comes with the next milestone (maybe april).

Cheers
Jörg

**Comment by marcobuss** [comment]
hi,

i will do it until next week but i dont understand why somebody should use it that way. There is no difference between copy a configuration jar and copy all configuration files to every project.

Cheers
Marco

**Comment by russt** [comment]
can you provide an example of how to do that?

my understanding was the only way to do this was to install the jar into the local repostiory, instead of pulling it from the source tree, which is what I needed.

thanks!
-Russ

At 11:14 AM -0800 3/10/12, Marco Buss wrote:

**Comment by marcobuss** [comment]
The default way to provide tomcat configuration e.g. setting JNDI resources in context.xml is to copy your configurations under <projectroot>/src/main/tomcat.
This Dir will be copied into the tomcat root directory. So you can overwrite the default files with your project specific ones.

We used this to define a bunch of JMS and database resources in context.xml. Because we have a lot of projects we had to changed this configuration in every projekt if one resource has to be changed. So the configuration.jar feature is realy useful for us.

An example can be found here: https://github.com/t7mp/examples/tree/master/simple

Is this an adequate solution for your problem? If yes i won't implement this feature because i think providing the configuration as files in the configuration directory is the same as putting a jar with the configuration into the projekt.

**Comment by russt** [comment]
It is unclear to me that we are talking about the same issue.

In my case, I am using the t7 plugin to install and start-up a tomcat container.

This container needs certain local libraries in the class path.

To get them there, I use the <libs> configuration element.

The <libs> element works like a standard maven dependency declaration, and pulls jars from the maven build repository into tomcat/lib.

However, we have random jars that are not available in the maven public repositories that also need to go in tomcat/lib prior to startup.

The standard maven notation for pulling in these sorts of jars is to use the <systemPath> element  (i.e. http://maven.apache.org/ref/3.0.4/maven-model/maven.html#class_dependency ).

Unless I am missing something, this has nothing to do with context files or JNDI resources.

thanks!
-Russ

At 3:28 PM -0800 3/10/12, Marco Buss wrote:

**Comment by marcobuss** [comment]
Ok, i missunderstood the issue. Now it is clear to me. Verry usefull feature I hope to get it done during the upcomming week.

**Comment by jbellmann** [comment]
Hi all,

I implemented this feature in the last days. Russt can you please verify that it works for you. You can find an example configuration [here](https://github.com/t7mp/maven-t7-plugin/blob/maven-t7-plugin-0.9.10.M2/src/it/systempath/pom.xml). It is not necessary to specify an 'scope'. That makes no sense in this case.
Let us know and reopen this issue if it do not work for you. The version you have to use is 0.9.10.M2. That version should be available in central on monday.

Cheers
Jörg

**Comment by russt** [comment]
Hi Jörg,

I'm getting the exception below.  Did something not get packed?

```
java.lang.ClassNotFoundException: com.googlecode.t7mp.maven.JarArtifact
```

thanks,
-Russ

# shasum m2/repository/com/googlecode/t7mp/maven-t7-plugin/0.9.10.M2/maven-t7-plugin-0.9.10.M2.jar

34e048be24178cec1bbb053dd289982e56ce7729  m2/repository/com/googlecode/t7mp/maven-t7-plugin/0.9.10.M2/maven-t7-plugin-0.9.10.M2.jar

# cat m2/repository/com/googlecode/t7mp/maven-t7-plugin/0.9.10.M2/maven-t7-plugin-0.9.10.M2.jar.sha1

34e048be24178cec1bbb053dd289982e56ce7729

jar tf m2/repository/com/googlecode/t7mp/maven-t7-plugin/0.9.10.M2/maven-t7-plugin-0.9.10.M2.jar
META-INF/
META-INF/MANIFEST.MF
com/
com/googlecode/
com/googlecode/t7mp/
com/googlecode/t7mp/conf/
com/googlecode/t7mp/maven/
META-INF/maven/
com/googlecode/t7mp/artifacts.properties
com/googlecode/t7mp/conf/catalina.policy
com/googlecode/t7mp/conf/catalina.properties
com/googlecode/t7mp/conf/context.xml
com/googlecode/t7mp/conf/logging.properties
com/googlecode/t7mp/conf/server.xml
com/googlecode/t7mp/conf/tomcat-users.xml
com/googlecode/t7mp/conf/web.xml
com/googlecode/t7mp/maven/AbstractT7BaseMojo.class
com/googlecode/t7mp/maven/AbstractT7TomcatMojo.class
com/googlecode/t7mp/maven/CheckT7ArtifactsStep.class
com/googlecode/t7mp/maven/DefaultMavenPluginContext.class
com/googlecode/t7mp/maven/FindVersionPredicate.class
com/googlecode/t7mp/maven/ForkedSetupSequence.class
com/googlecode/t7mp/maven/MavenPluginContext.class
com/googlecode/t7mp/maven/MavenPluginLog.class
com/googlecode/t7mp/maven/MavenTomcatSetupSequence.class
com/googlecode/t7mp/maven/MyArtifactResolver.class
com/googlecode/t7mp/maven/NoVersionPredicate.class
com/googlecode/t7mp/maven/PreConditions.class
com/googlecode/t7mp/maven/RunForkedMojo$Runner.class
com/googlecode/t7mp/maven/RunForkedMojo.class
com/googlecode/t7mp/maven/RunMojo.class
com/googlecode/t7mp/maven/StopForkedMojo.class
com/googlecode/t7mp/maven/StopMojo.class
com/googlecode/t7mp/tomcat_6.0.32.properties
com/googlecode/t7mp/tomcat_6.properties
com/googlecode/t7mp/tomcat_7.properties
META-INF/maven/plugin.xml
META-INF/maven/com.googlecode.t7mp/
META-INF/maven/com.googlecode.t7mp/maven-t7-plugin/
META-INF/maven/com.googlecode.t7mp/maven-t7-plugin/pom.xml
META-INF/maven/com.googlecode.t7mp/maven-t7-plugin/pom.properties

[DEBUG] Configuring mojo 'com.googlecode.t7mp:maven-t7-plugin:0.9.10.M2:run-forked' -->
[DEBUG](s) addGithubRepository = false
[DEBUG](s) buildFinalName = tomcat-test-instance-630-SNAPSHOT
[DEBUG](s) catalinaBase = /demo2/iii-top/webapps/test/tomcat/target/tomcat
[DEBUG](s) contextPath = tomcat-test-instance-630-SNAPSHOT
[DEBUG](s) downloadTomcatExamples = false
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to configure plugin parameters for: com.googlecode.t7mp:maven-t7-plugin:0.9.10.M2

Cause: Error loading class 'com.googlecode.t7mp.maven.JarArtifact'
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error configuring: com.googlecode.t7mp:maven-t7-plugin. Reason: Unable to parse the created DOM for plugin configuration
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:723)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
    at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.PluginConfigurationException: Error configuring: com.googlecode.t7mp:maven-t7-plugin. Reason: Unable to parse the created DOM for plugin configuration
    at org.apache.maven.plugin.DefaultPluginManager.populatePluginFields(DefaultPluginManager.java:1363)
    at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:724)
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:468)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
    ... 17 more
Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Error loading class 'com.googlecode.t7mp.maven.JarArtifact'
    at org.codehaus.plexus.component.configurator.converters.composite.CollectionConverter.fromConfiguration(CollectionConverter.java:170)
    at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.configure(ComponentValueSetter.java:207)
    at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:137)
    at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:56)
    at org.apache.maven.plugin.DefaultPluginManager.populatePluginFields(DefaultPluginManager.java:1357)
    ... 20 more
Caused by: java.lang.ClassNotFoundException: com.googlecode.t7mp.maven.JarArtifact
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at org.codehaus.classworlds.RealmClassLoader.loadClassDirect(RealmClassLoader.java:195)
    at org.codehaus.classworlds.DefaultClassRealm.loadClass(DefaultClassRealm.java:255)
    at org.codehaus.classworlds.DefaultClassRealm.loadClass(DefaultClassRealm.java:274)
    at org.codehaus.classworlds.RealmClassLoader.loadClass(RealmClassLoader.java:214)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at org.codehaus.plexus.component.configurator.converters.composite.CollectionConverter.fromConfiguration(CollectionConverter.java:158)
    ... 24 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5 seconds
[INFO] Finished at: Mon Mar 26 14:25:52 PDT 2012
[INFO] Final Memory: 25M/81M
[INFO] ------------------------------------------------------------------------

At 4:44 PM -0700 3/24/12, Jörg Bellmann wrote:

**Comment by jbellmann** [comment]
Hi russt,

thanks for your response. I will have a look what's going wrong.

Cheers
Jörg

**Comment by jbellmann** [comment]
Hi Russ,

sorry but I couldn't reproduce the exception. I added one more integration-test for running in forked mode but all integration-tests were successful. I also use the specified version (0.9.10.M2) on the examples project. Without any exception. All my tests were executed with Maven 3.0.4. What version do you use?

Cheers
Jörg

**Comment by jbellmann** [comment]
Hi Marco,

can you please verify that version 0.9.10.M2 works?
Thank you.

MfG
Jörg

**Comment by russt** [comment]
we are using maven 2.2.1.
previous version of the plugin works fine.

thanks,
-Russ

At 12:10 PM -0700 3/27/12, Jörg Bellmann wrote:

**Comment by jbellmann** [comment]
Hi Russ,

I hope the latest release 0.9.10.M3 works better for you ;-). The tests passed successfully with Maven 2. Please try again when the plugin will be available at [central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.googlecode.t7mp%22%20AND%20a%3A%22maven-t7-plugin%22).

Cheers
Jörg

**Comment by russt** [comment]
At 11:13 PM -0700 3/29/12, Jörg Bellmann wrote:

> Hi Russ,
> 
> I hope the latest release 0.9.10.M3 works better for you ;-). The tests passed successfully with Maven 2. Please try again when the plugin will be available at (central) [http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.googlecode.t7mp%22%20AND%20a%3A%22maven-t7-plugin%22].

Jörg,

yes, this one worked perfectly.  :-)

this saves me the custom step to prime the repo with these custom jars.

I really appreciate it!

best,
-Russ

Resolve artifact for JarArtifact[commons-collections:commons-collections:jar:2.1]
Resolve artifact for JarArtifact[commons-pool:commons-pool:jar:1.0.1]
Resolve artifact for JarArtifact[commons-dbcp:commons-dbcp:jar:1.0]
Resolve artifact for JarArtifact[/mybuild/dist/Tomcat/common/lib/custom_manager.jar]
Resolve artifact for JarArtifact[/mybuild/dist/Tomcat/common/lib/custom_mysql.jar]
Resolve artifact for JarArtifact[/mybuild/dist/Tomcat/common/lib/custom_postgresql.jar]
Resolve artifact for JarArtifact[/mybuild/dist/Tomcat/common/lib/custom_resources.jar]
Copy artifact from /myrepo/commons-collections/commons-collections/2.1/commons-collections-2.1.jar to /mybuild/webapps/test/tomcat/target/tomcat/lib/commons-collections-2.1.jar
Copy artifact from /myrepo/commons-pool/commons-pool/1.0.1/commons-pool-1.0.1.jar to /mybuild/webapps/test/tomcat/target/tomcat/lib/commons-pool-1.0.1.jar
Copy artifact from /myrepo/commons-dbcp/commons-dbcp/1.0/commons-dbcp-1.0.jar to /mybuild/webapps/test/tomcat/target/tomcat/lib/commons-dbcp-1.0.jar
Copy artifact from /mybuild/dist/Tomcat/common/lib/custom_manager.jar to /mybuild/webapps/test/tomcat/target/tomcat/lib/custom_manager-1.0.jar
Copy artifact from /mybuild/dist/Tomcat/common/lib/custom_mysql.jar to /mybuild/webapps/test/tomcat/target/tomcat/lib/custom_mysql-1.0.jar
Copy artifact from /mybuild/dist/Tomcat/common/lib/custom_postgresql.jar to /mybuild/webapps/test/tomcat/target/tomcat/lib/custom_postgresql-1.0.jar
Copy artifact from /mybuild/dist/Tomcat/common/lib/custom_resources.jar to /mybuild/webapps/test/tomcat/target/tomcat/lib/custom_resources-1.0.jar

CONFIGURATION:

<build>
    <plugins>
        <plugin>
            <groupId>com.googlecode.t7mp</groupId>
            <artifactId>maven-t7-plugin</artifactId>
            <configuration>
                <libs>
                    <jarArtifact>
                        <groupId>commons-collections</groupId>
                        <artifactId>commons-collections</artifactId>
                        <version>2.1</version>
                    </jarArtifact>
                    <jarArtifact>
                        <groupId>commons-pool</groupId>
                        <artifactId>commons-pool</artifactId>
                        <version>1.0.1</version>
                    </jarArtifact>
                    <jarArtifact>
                        <groupId>commons-dbcp</groupId>
                        <artifactId>commons-dbcp</artifactId>
                        <version>1.0</version>
                    </jarArtifact>
                    <jarArtifact>
                        <groupId>com.custom</groupId>
                        <version>1.0</version>
                        <artifactId>custommanager</artifactId>
                        <systemPath>${SRCROOT}/dist/Tomcat/common/lib/custommanager.jar</systemPath>
                    </jarArtifact>
                    <jarArtifact>
                        <groupId>com.custom</groupId>
                        <version>1.0</version>
                        <artifactId>custommysql</artifactId>
                        <systemPath>${SRCROOT}/dist/Tomcat/common/lib/custommysql.jar</systemPath>
                    </jarArtifact>
                    <jarArtifact>
                        <groupId>com.custom</groupId>
                        <version>1.0</version>
                        <artifactId>custompostgresql</artifactId>
                        <systemPath>${SRCROOT}/dist/Tomcat/common/lib/custompostgresql.jar</systemPath>
                    </jarArtifact>
                    <jarArtifact>
                        <groupId>com.custom</groupId>
                        <version>1.0</version>
                        <artifactId>customresources</artifactId>
                        <systemPath>${SRCROOT}/dist/Tomcat/common/lib/customresources.jar</systemPath>
                    </jarArtifact>
                </libs>
                ...
