### ISSUE TITLE
Can not run with tomcat version 6.0.20

### ISSUE THREAD

**Issue by ishara** [t7mp/t7mp#55]
Hi 

Can I run with tomcat version 6.0.20 ? 

I got the fallowing error .

Could not resolve artifact with coordinates com.googlecode.t7mp:tomcat:zip:6.0.2
0.A
com.googlecode.t7mp.configuration.ResolutionException: Could not resolve artifac
t with coordinates com.googlecode.t7mp:tomcat:zip:6.0.20.A
        at com.googlecode.t7mp.configuration.ChainedArtifactResolver.resolveArti
fact(ChainedArtifactResolver.java:52)
        at com.googlecode.t7mp.steps.deployment.ResolveTomcatStep.execute(Resolv
eTomcatStep.java:71)
        at com.googlecode.t7mp.steps.DefaultStepSequence.execute(DefaultStepSequ
ence.java:35)
        at com.googlecode.t7mp.steps.DefaultStepSequence.execute(DefaultStepSequ
ence.java:35)
        at com.googlecode.t7mp.RunMojo.execute(RunMojo.java:52)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default

Thank you

Note -  6.0.24 working fine.

**Comment by jbellmann** [comment]
Hi Ishara,

as mentioned in the [docu](http://t7mp.github.com/docu/html/ch01.html#d4e39) we only support 6.0.24 and higher. We had some issues with the automatic checksum-test on our tomcat-download-repackage-upload-cycle.

Easiest way would be to install a 6.0.20.zip in your local maven-repository with the following maven-coordinates:
groupId: com.googlecode.t7mp
artifactId: tomcat
version: 6.0.20
type: zip

Then specify the 'tomcatVersion'-config-element to 6.0.20 and it should work.

Cheers
Jörg

**Comment by jbellmann** [comment]
Hi Ishara,

please let us know if the comments where helpful or when you have further questions. Please close the isssues you openened. We can better sleep then. ;-)

Cheers
Jörg
