### ISSUE TITLE
mvn t7:stop not working

### ISSUE THREAD

**Issue by ishara** [t7mp/t7mp#57]
Seems t7:stop not working. 
I am using -0.9.10.M3  and Windows 7

I have try with tomcat version 6.0.24 and 7.0.22

How can I use <tomcatShutdownCommand>SHUTDOWN</tomcatShutdownCommand> ?

Thank you

**Comment by jbellmann** [comment]
Hi Ishara,

what makes you thinking that it does not work? Do you see any exceptions?

Cheers
Jörg

**Comment by ishara** [comment]
Hi Jörg

I start tomcat  as fallow (run in background). 

mvn t7:run >> outlog.log 2>&1 &

And try to stop tomcat using 

mvn t7:stop

No errors, maven report SUCESS,  but tomcat instance is running and  need to kill with task manager.

Please advice.
Thank you

**Comment by jbellmann** [comment]
Thanks,

maybe I can reproduce this behavior.
One question: Why do you redirect the output to 'outlog.log' in the background?

Cheers
Jörg

**Comment by jbellmann** [comment]
Hi Ishara,

't7:run' and 't7:stop' are used for starting tomcat in the same process as maven. So with your command 'mvn t7:run >> outlog.log 2>&1 &' you put this process in the background. When you then later call 'mvn t7:stop' you start a new maven-process and there will be no reference in the maven-plugin-context which can be used to stop the tomcat.

In the next release (thursday) I will log this behavior explicit. So a user will see that he or she is doing something strange with the plugin. If there is a reason for doing so like you did, you can then use 't7:stop-forked' to stop the 'background-tomcat-instance'.

But I would prefer to configure 'tomcatSetAwait' to false and then use 't7:run-forked' to start a Tomcat-Instance and 't7:stop-forked' to stop it. Tomcat will be then started in background. (also in the next release)

Cheers
Jörg

**Comment by ishara** [comment]
Hi Jörg

We have huge log  and need to see log for error detection. Our development team already use 'tail -f output.log'  monitor logs. Now I have to open two console for tomcat run and see out log.

That's why I have try this way to avoid two consoles.      

Thank you
Ishara

**Comment by jbellmann** [comment]
Hi Ishara,

0.9.10.M5 is in maven-central and you can use. It should be possible now to use 'mvn t7:stop-forked' for your special purposes.
Seems to me, I have to invest more time in documentation, right?

Please reopen this issue if you think it doesn't work but please describe a bit more what you did, what you were expecting and what really happen (and a stacktrace if you have one).

Cheers Jörg
