### ISSUE TITLE
Deploying 'external' war files

### ISSUE THREAD

**Issue by surfsoft** [t7mp/t7mp#59]
Scenario: A multi-module maven project builds a WAR file for which I have Geb acceptance tests. A Jenkins build performs the build and runs the acceptance tests using the t7 plugin.

Now I need to deploy a dependancy (another webapp, already packaged in a WAR file) in the same container for the duration of the tests. The dependancy is not part of this multi-module project and is build by another Jenkins job. My plan is to use Jenkins' Copy Artifacts plugin to obtain the latest build of the dependancy to make it available.

How can I configure the t7 plugin to deploy this external dependancy to a specific context?

**Comment by surfsoft** [comment]
OK daft question, I just needed to identify the module using its maven group and artifact and it got pulled from the repo.

**Comment by jbellmann** [comment]
Nice avatar ;-)

Thanks for using 'maven-t7-plugin'.

Jörg
