### ISSUE TITLE
CATALINA_OPTS for JVM argument like memory for large applications

### ISSUE THREAD

**Issue by marcobuss** [t7mp/t7mp#6]
MOVED FROM GOOGLECODE:

Reported by mailt...@gmail.com, Feb 09, 2011

No information/configuration for JVM argument for tomcat container. It is pretty common that a large web application can not work on default JVM memory.

**Comment by marcobuss** [comment]
As an quick fix use the MAVEN_OPTS to increase JVM-Memory.

In default Maven settings my configuration with 3 additional Webapps causes an PermGen OOM. Then i increased the PermGen with MAVEN_OPTS and everithing works fine.

e.g. for OSX i add the follwoing to my .bash_profile
export MAVEN_OPTS='-Xmx1024M -XX:MaxPermSize=256m'

**Comment by t7mp** [comment]
Marco, I think this not only a quick-fix, it is the preferred way to increase memory settings for maven. I will add this to the documentation.
