### ISSUE TITLE
Configuration property for hostname

### ISSUE THREAD

**Issue by surfsoft** [t7mp/t7mp#61]
Can you consider adding a configuration property for the host name? T7 generates a server.xml file every time it runs, with an Engine block that looks like this:
    <Engine name="Catalina" defaultHost="localhost">

and a Host block that looks like this:
    <Host name="localhost"  appBase="webapps" unpackWARs="true" autoDeploy="true">

What I really need is to be able to replace localhost with an IP address, I've been trying to reproduce a browser defect on a Windows virtual machine. Now that VM runs on the same box where I'm running mvn t7:run but clearly it can't receive resources from 'localhost' with the result that nothing works in my (javascript heavy) webapp.

So what I'd like to see is a configuration line that looks something like this:
    <tomcatHostName>10.0.1.123</tomcatHostName\>

And a server.xml with: 
    <Engine name="Catalina" defaultHost="${tomcatHostName}">
        ...
        <Host name="${tomcatHostName}"  appBase="webapps" unpackWARs="true" autoDeploy="true">

With tomcatHostName defaulting to 'localhost'.

Thanks.

**Comment by jbellmann** [comment]
Hi Phil,

sure, should be possible as we do with the 'httpPort' and the 'shutdownPort'.
Maybe I will find some time in the next days.

Cheers
Jörg

**Comment by jbellmann** [comment]
Hi Phil,

try the latest SNAPSHOT (0.9.10-SNAPSHOT) from the sonatype-oss-snapshot-repository

https://oss.sonatype.org/content/repositories/snapshots

Cheers
Jörg

**Comment by jbellmann** [comment]
Hi Phil,

I released a new milestone (0.9.10.M6). Simply put a `<tomcatHostName>yourHost</tomcatHostName>` in the configuration-section.

Cheers
Jörg

**Comment by surfsoft** [comment]
Jörg,

I'm unable to try it out right at this moment but will do so in the next 24
hours and let you know. Really appreciate the effort, thanks very much.

Phil.

On Sun, Jul 22, 2012 at 9:27 PM, Jörg Bellmann <
reply@reply.github.com

> wrote:
> 
> Hi Phil,
> 
> I released a new milestone (0.9.10.M6). Simply put a
> `<tomcatHostName>yourHost</tomcatHostName>` in the configuration-section.
> 
> Cheers
> Jörg
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/t7mp/t7mp/issues/61#issuecomment-7165285

## 

Phil Haigh
Surfsoft Consulting Ltd
Phone: +44 (0)78 9004 2675
Web: www.surfsoftconsulting.com

**Comment by jbellmann** [comment]
Hi Surfsoft,

do you tried it? Please close the Issue if it's working.

Cheers
Jörg

**Comment by surfsoft** [comment]
Hi Jörg

Sorry for the delayed reply, I'm on holiday at the moment. Yes, this did
what I needed, along with some hacking of my VM's config. Many thanks.

Phil.
