### ISSUE TITLE
Command mvn t7:restart-forked not found

### ISSUE THREAD

**Issue by kaleeswaran14** [t7mp/t7mp#62]
Hi,

I am using t7 plugin of version 0.9.9. 

<groupId>com.googlecode.t7mp</groupId>
<artifactId>maven-t7-plugin</artifactId>
<version>0.9.9</version>

Is there anyother way to restart it. 

Is there any command on this plugin ?

Thanks.

**Comment by marcobuss** [comment]
Hi,

there is no t7:restart-forked goal available yet.

You can use "t7:stop-forked" followed by a "t7:start-forked"

**Comment by jbellmann** [comment]
Hi,

I generated and published the site for the plugin. For an overview of all goals [see](http://t7mp.github.com/plugin-info.html).

Hope that helps.

Thanks Marco for being faster than 'MeinerEiner' ;-)

MfG
Jörg
