### ISSUE TITLE
t7mp with Jprofile

### ISSUE THREAD

**Issue by ishara** [t7mp/t7mp#68]
Hi

How can I profile tomcat using tool like Jprofile (http://www.ej-technologies.com/products/jprofiler/overview.html)

Or Visual VM

Thank you

**Comment by jbellmann** [comment]
Hi Ishara,

you should visit the documentation of JProfiler to get this information. If the Tomcat-Instance has to be configured with special options and you don't know how to configure Tomcat(t7mp) with that settings than you can ask again. Thats our part then.

There are some threads on StackOverflow maybe.

Cheers Jörg

**Comment by ishara** [comment]
Hi Cheers Jörg

I have add some changes to startup.bat , but when I start mvn t7:run , startup.bat changes are clean with fresh one.

Thank you

**Comment by jbellmann** [comment]
Hi Ishara,

you can specify your 'OPTIONS' in a 'setenv.bat/.sh' file under 'src/tomcat/bin'. It will be copied to the Instance and then hoperfully used. ;-)
See also #51 on how to set JVM-Options. There are also links to the example-project.

Hope that helps

Cheers
Jörg
