### ISSUE TITLE
Support for oppening tomcat as debug mode

### ISSUE THREAD

**Issue by leCandas** [t7mp/t7mp#69]
It will be perfect to have mvn t7:debug option

**Comment by marcobuss** [comment]
use mvndebug instead of mvn and be happy.

**Comment by leCandas** [comment]
I guess you misunderstand me, I mean oppening tomcat in debug mode, for remote debuging. Like using this command "catalina.bat jpda start"

**Comment by marcobuss** [comment]
No, ist extactly what mvndebug offers.
The whole mvn process starts in debug mode and also the tomcat process. An alternative is to use JAVA-OPTS like described in #51

**Comment by jbellmann** [comment]
Hi,

maybe this [step by step tutorial](http://jbellmann.wordpress.com/2012/09/17/how-to-debug-an-java-webapplication-running-with-maven-t7-plugin-in-eclipse/) can help.

Cheers
Jörg

**Comment by leCandas** [comment]
Thank you very much Jörg and Marco, for both plugin and help.
