### ISSUE TITLE
Can't redirect tomcat console output to logs

### ISSUE THREAD

**Issue by marcobuss** [t7mp/t7mp#7]
MOVED FROM GOOGLECODE:

Reported by mailt...@gmail.com, Feb 10, 2011

I would like to have a configuration using which I can redirect the tomcat console output to a log file, I am trying to use t7mp for automated UI acceptance tests and there are lot's of tests which runs will cause mvn console output to look very bad because of large log output

**Comment by t7mp** [comment]
Marco,

do you have any ideas? Maybe we should use log4j to make this a bit more user-friendly?

MfG
Jörg

**Comment by marcobuss** [comment]
I think Tomcat uses log4j to log. I think we can achiv this with an appropriate log4j configuration.

**Comment by t7mp** [comment]
No, I think it uses a repackaged version of commons-logging or juli. There is an extra-package at the downloads to use log4j. Maybe we should integrate it in our plugin to improve the user experience.

**Comment by jbellmann** [comment]
It's now configurable to suspend the console output.
