### ISSUE TITLE
WAR files get redeployed while Tomcat is running

### ISSUE THREAD

**Issue by sparhomenko** [t7mp/t7mp#70]
We ran into a problem while running our integration test suite with t7mp (version 0.9.10.M8). Tests in the suite were failing because Tomcat returned 404 responses to certain requests. Failures was intermittent, but always started 20-30 seconds after suite started, and lasted for about 5 seconds. The failure was only reproducible on Windows developer machines, Mac OS did not have the problem.
After spending some time debugging the issue, we found that Tomcat attempts to redeploy the WAR while the tests are running, thus returning 404 while redeployment is in progress. It does so because the WAR last modified date is changed, and Tomcat background thread which monitors WAR files in `/webapps/` detects that and triggers the redeployment.
It is not quite clear who touches the WAR file and updates the date. However, checking the source code file [`WebappsDeploymentStep`](https://github.com/t7mp/maven-t7-plugin/blob/master/src/main/java/com/googlecode/t7mp/steps/WebappsDeploymentStep.java), line 68, we found two streams (`FileInputStream` and `FileOutputStream`) being opened, and never closed. They are probably closed later on by the garbage collector, which causes some remaining `FileOutputStream` bytes to be flushed, updating last modified date of the WAR file, causing the redeployment and ultimately causing test failure.

We tried to patch the t7mp Maven artifact by using [`CommonsSetupUtil`](https://github.com/t7mp/maven-t7-plugin/blob/master/src/main/java/com/googlecode/t7mp/util/CommonsSetupUtil.java) `.copyFile()` instead of `.copy()`, which should take care both of opening and closing the streams whenever necessary. This fix seems to be fixing the problem for us. We would like to avoid using a patched artifact though, so it would be very nice if the same fix can be applied in one of the future releases of t7mp.
Sorry for not providing a unit test, it is quite hard to implement a proper one to consistently reproduce the issue as it depends on OS (file system), JDK (garbage collector) and timing (when GC kicks in and how long it takes Tomcat to redeploy). It is also a one-line change which seems to be necessary just by looking on the code. If you would find it useful we can provide a pull request.

**Comment by jbellmann** [comment]
Happy new year,

I just released 0.9.12 with closing both streams in 'CommonsSetupUtil'. So I hope that will fix the problem you described above.
Please test against that version and let me know when it works.

Cheers
Jörg

**Comment by marcobuss** [comment]
Verry nice error tracing. Thank you.

**Comment by sparhomenko** [comment]
Happy New Year gentlemen,

Thanks for a surprisingly fast feedback. I've tried out 0.9.12 and it works fine, closing the issue.
