### ISSUE TITLE
Support Tomcat 7.0.37

### ISSUE THREAD

**Issue by ggerard** [t7mp/t7mp#71]
7.0.32 seems to be the latest that Maven.

https://oss.sonatype.org/content/repositories/releases/com/googlecode/t7mp/tomcat/

**Comment by marcobuss** [comment]
If you need it right now use 'tomcatVersion'

&lt;plugin&gt;
...
   &lt;configuration&gt;
      &lt;tomcatVersion&gt;7.0.32&lt;/tomcatVersion&gt;
   &lt;/configuration&gt;
&lt;/plugin&gt;

**Comment by jbellmann** [comment]
Hi all,

7.0.33, 7.0.34, 7.0.35 and 7.0.37 are now available in central. So set the 'tomcatVersion' to the version you want as Marco wrote before.

Cheers
Jörg
