### ISSUE TITLE
No 'jasper-jdt' in maven-central

### ISSUE THREAD

**Issue by ghost** [t7mp/t7mp#8]
From version 6.0.30 tomcat don't use 'jasper-jdt' as a library. That causes errors when resolving version of tomcat higher than 6.0.29 because 'jasper-jdt' does not exist in maven-central.

**Comment by t7mp** [comment]
We pushed a repackaged version of ecj to maven-central. So we can fix all that issues.

**Comment by t7mp** [comment]
Seems that we can close the issue. The repackaged version works for me.
